### ISSUE TITLE
Ethernet randomly down on boot

### ISSUE THREAD

**Issue by ledge74** [quanghd96/Hackintosh-B460M-BAZOOKA-i3-10100-iGPU-UHD630#1]
Hello @quanghd96, thanks for making your EFI public, it's helping me greatly with building my first hackintosh with the same motherboard. 

Did you manage to get ethernet working perfectly ? On my machine with the same kexts as you, ethernet is randomly shutting down on boot. I have to unplug / plug again the cable to make it work again (I configured the ethernet hardware same as your readme).

**Comment by quanghd96** [comment]
Please check my config
![image](https://user-images.githubusercontent.com/15941383/104887815-7fdfa480-599e-11eb-9806-43460c59f69b.png)
