### ISSUE TITLE
能更新到11.2吗 或者后续还有更新吗

### ISSUE THREAD

**Issue by alpha302** [quanghd96/Hackintosh-B460M-BAZOOKA-i3-10100-iGPU-UHD630#2]

**Comment by quanghd96** [comment]
Please wait next release. Thanks!

**Comment by alpha302** [comment]
thank you for you reply



在 2021-03-15 12:18:09，"Đặng Ngọc Quảng" ***@***.***> 写道：

Please wait next release. Thanks!

**Comment by quanghd96** [comment]
I've released version 11.2.3 with OpenCore 0.6.7. You can download from: [https://github.com/quanghd96/Hackintosh-B460M-BAZOOKA-i3-10100-iGPU-UHD630/releases/tag/11.2.3](url)
![image](https://user-images.githubusercontent.com/15941383/114159845-6ff9b000-9950-11eb-830f-af9540312bee.png)

**Comment by alpha302** [comment]
> I've released version 11.2.3 with OpenCore 0.6.7. You can download from: [https://github.com/quanghd96/Hackintosh-B460M-BAZOOKA-i3-10100-iGPU-UHD630/releases/tag/11.2.3](url)
> ![image](https://user-images.githubusercontent.com/15941383/114159845-6ff9b000-9950-11eb-830f-af9540312bee.png)

think you
