### ISSUE TITLE
Can I use NVMe SSD? 

### ISSUE THREAD

**Issue by codenamem27** [quanghd96/Hackintosh-B460M-BAZOOKA-i3-10100-iGPU-UHD630#6]
As per title. 
Thanks!

**Comment by quanghd96** [comment]
Yes. I am using it

**Comment by codenamem27** [comment]
Thanks for the quick reply. 
Which brand of SSD is it? I previously heard Samsung one has some issue.

**Comment by quanghd96** [comment]
You can check this: https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html

**Comment by codenamem27** [comment]
All good, thank you!
